# Generated by Django 5.1.4 on 2025-01-20 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('instrumentos', '0001_initial'),
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comodatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato', models.CharField(max_length=150)),
                ('compra_minima_mensual_dinero', models.IntegerField()),
                ('compra_minima_mensual_reactivos', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('is_renovable', models.BooleanField()),
                ('is_renovable_automatico', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.estados')),
            ],
        ),
        migrations.CreateModel(
            name='ComodatosInstrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_neto', models.IntegerField()),
                ('comodato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comodatos.comodatos')),
                ('instrumentos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrumentos.instrumentos')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.monedas')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.ubicaciones')),
            ],
        ),
    ]
