# Generated by Django 5.1.4 on 2025-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=50)),
                ('codigo_comuna', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
