# Generated by Django 5.1.4 on 2025-01-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('adn', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('serie', models.CharField(max_length=50)),
            ],
        ),
    ]
